INSERT INTO trips (destination, distance) VALUES ('London', '35');
INSERT INTO trips (destination, distance) VALUES ('Phuket', '28');
INSERT INTO trips (destination, distance) VALUES ('Bali', '45');
INSERT INTO trips (destination, distance) VALUES ('New York', '29');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '26');
INSERT INTO trips (destination, distance) VALUES ('Paris', '42');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '33');
INSERT INTO trips (destination, distance) VALUES ('Rio de Janeiro', '25');
INSERT INTO trips (destination, distance) VALUES ('Amsterdam', '31');
INSERT INTO trips (destination, distance) VALUES ('Dubai', '39');
INSERT INTO trips (destination, distance) VALUES ('Cancun', '27');
INSERT INTO trips (destination, distance) VALUES ('Barcelona', '36');
INSERT INTO trips (destination, distance) VALUES ('Honolulu', '29');
INSERT INTO trips (destination, distance) VALUES ('Berlin', '48');
INSERT INTO trips (destination, distance) VALUES ('Marrakech', '26');
INSERT INTO trips (destination, distance) VALUES ('Edinburgh', '32');
INSERT INTO trips (destination, distance) VALUES ('Paris', '30');
INSERT INTO trips (destination, distance) VALUES ('Bali', '28');
INSERT INTO trips (destination, distance) VALUES ('London', '35');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '45');
INSERT INTO trips (destination, distance) VALUES ('New York', '27');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '32');
INSERT INTO trips (destination, distance) VALUES ('Rome', '29');
INSERT INTO trips (destination, distance) VALUES ('Bangkok', '40');
INSERT INTO trips (destination, distance) VALUES ('Paris', '24');
INSERT INTO trips (destination, distance) VALUES ('Hawaii', '34');
INSERT INTO trips (destination, distance) VALUES ('Barcelona', '31');
INSERT INTO trips (destination, distance) VALUES ('Japan', '30');
INSERT INTO trips (destination, distance) VALUES ('Thailand', '45');
INSERT INTO trips (destination, distance) VALUES ('France', '25');
INSERT INTO trips (destination, distance) VALUES ('Australia', '28');
INSERT INTO trips (destination, distance) VALUES ('Brazil', '33');
INSERT INTO trips (destination, distance) VALUES ('Greece', '20');
INSERT INTO trips (destination, distance) VALUES ('Egypt', '37');
INSERT INTO trips (destination, distance) VALUES ('Mexico', '42');
INSERT INTO trips (destination, distance) VALUES ('Italy', '31');
INSERT INTO trips (destination, distance) VALUES ('Spain', '27');
INSERT INTO trips (destination, distance) VALUES ('Canada', '38');
INSERT INTO trips (destination, distance) VALUES ('Paris', '25');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '33');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '28');
INSERT INTO trips (destination, distance) VALUES ('Cancun', '45');
INSERT INTO trips (destination, distance) VALUES ('Rio de Janeiro', '30');
INSERT INTO trips (destination, distance) VALUES ('London', '55');
INSERT INTO trips (destination, distance) VALUES ('Barcelona', '27');
INSERT INTO trips (destination, distance) VALUES ('New York City', '41');
INSERT INTO trips (destination, distance) VALUES ('Bangkok', '29');
INSERT INTO trips (destination, distance) VALUES ('Vancouver', '24');
INSERT INTO trips (destination, distance) VALUES ('Amsterdam', '31');
INSERT INTO trips (destination, distance) VALUES ('Paris', '31');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '25');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '27');
INSERT INTO trips (destination, distance) VALUES ('New York', '28');
INSERT INTO trips (destination, distance) VALUES ('Rio de Janeiro', '30');
INSERT INTO trips (destination, distance) VALUES ('Bangkok', '23');
INSERT INTO trips (destination, distance) VALUES ('London', '35');
INSERT INTO trips (destination, distance) VALUES ('Barcelona', '29');
INSERT INTO trips (destination, distance) VALUES ('Seoul', '27');
INSERT INTO trips (destination, distance) VALUES ('Los Angeles', '26');
INSERT INTO trips (destination, distance) VALUES ('Rome', '33');
INSERT INTO trips (destination, distance) VALUES ('Paris', '35');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '28');
INSERT INTO trips (destination, distance) VALUES ('Cape Town', '29');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '43');
INSERT INTO trips (destination, distance) VALUES ('Barcelona', '31');
INSERT INTO trips (destination, distance) VALUES ('Bali', '27');
INSERT INTO trips (destination, distance) VALUES ('Paris', '39');
INSERT INTO trips (destination, distance) VALUES ('New York', '25');
INSERT INTO trips (destination, distance) VALUES ('Bangkok', '33');
INSERT INTO trips (destination, distance) VALUES ('Rome', '41');
INSERT INTO trips (destination, distance) VALUES ('Bali', '37');
INSERT INTO trips (destination, distance) VALUES ('Bali', '35');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '29');
INSERT INTO trips (destination, distance) VALUES ('Cancun', '42');
INSERT INTO trips (destination, distance) VALUES ('Paris', '46');
INSERT INTO trips (destination, distance) VALUES ('Cape Town', '31');
INSERT INTO trips (destination, distance) VALUES ('Bali', '25');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '38');
INSERT INTO trips (destination, distance) VALUES ('Bangkok', '27');
INSERT INTO trips (destination, distance) VALUES ('New York', '60');
INSERT INTO trips (destination, distance) VALUES ('Phuket', '32');
INSERT INTO trips (destination, distance) VALUES ('Rome', '41');
INSERT INTO trips (destination, distance) VALUES ('Paris', '35');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '28');
INSERT INTO trips (destination, distance) VALUES ('Bali', '42');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '45');
INSERT INTO trips (destination, distance) VALUES ('New York', '31');
INSERT INTO trips (destination, distance) VALUES ('London', '29');
INSERT INTO trips (destination, distance) VALUES ('Dubai', '24');
INSERT INTO trips (destination, distance) VALUES ('Bangkok', '26');
INSERT INTO trips (destination, distance) VALUES ('Rome', '30');
INSERT INTO trips (destination, distance) VALUES ('Bali', '33');
INSERT INTO trips (destination, distance) VALUES ('Seoul', '27');
INSERT INTO trips (destination, distance) VALUES ('Paris', '35');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '28');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '45');
INSERT INTO trips (destination, distance) VALUES ('London', '37');
INSERT INTO trips (destination, distance) VALUES ('New York', '50');
INSERT INTO trips (destination, distance) VALUES ('Rome', '31');
INSERT INTO trips (destination, distance) VALUES ('Bangkok', '42');
INSERT INTO trips (destination, distance) VALUES ('Cape Town', '27');
INSERT INTO trips (destination, distance) VALUES ('Rio de Janeiro', '33');
INSERT INTO trips (destination, distance) VALUES ('Bali', '29');
INSERT INTO trips (destination, distance) VALUES ('Amsterdam', '41');
INSERT INTO trips (destination, distance) VALUES ('Paris', '35');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '28');
INSERT INTO trips (destination, distance) VALUES ('New York', '42');
INSERT INTO trips (destination, distance) VALUES ('Bali', '30');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '26');
INSERT INTO trips (destination, distance) VALUES ('London', '38');
INSERT INTO trips (destination, distance) VALUES ('Phuket', '45');
INSERT INTO trips (destination, distance) VALUES ('Rome', '31');
INSERT INTO trips (destination, distance) VALUES ('Santorini', '27');
INSERT INTO trips (destination, distance) VALUES ('Dubai', '29');
INSERT INTO trips (destination, distance) VALUES ('Phnom Penh', '33');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '32');
INSERT INTO trips (destination, distance) VALUES ('Paris', '47');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '26');
INSERT INTO trips (destination, distance) VALUES ('Rome', '38');
INSERT INTO trips (destination, distance) VALUES ('Bali', '29');
INSERT INTO trips (destination, distance) VALUES ('Cancun', '41');
INSERT INTO trips (destination, distance) VALUES ('Athens', '35');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '24');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '30');
INSERT INTO trips (destination, distance) VALUES ('Paris', '28');
INSERT INTO trips (destination, distance) VALUES ('Bali', '33');
INSERT INTO trips (destination, distance) VALUES ('Paris', '35');
INSERT INTO trips (destination, distance) VALUES ('Tokyo', '28');
INSERT INTO trips (destination, distance) VALUES ('Cape Town', '45');
INSERT INTO trips (destination, distance) VALUES ('Sydney', '31');
INSERT INTO trips (destination, distance) VALUES ('Rome', '42');
INSERT INTO trips (destination, distance) VALUES ('New York City', '27');
INSERT INTO trips (destination, distance) VALUES ('Rio de Janeiro', '37');
INSERT INTO trips (destination, distance) VALUES ('Vancouver', '29');
INSERT INTO trips (destination, distance) VALUES ('Bangkok', '34');
INSERT INTO trips (destination, distance) VALUES ('Barcelona', '25');
INSERT INTO trips (destination, distance) VALUES ('Auckland', '39');
